albums/urls.py
from django import contrib
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('musics.urls')),
    path('user/',include('user.urls')),
    path('user/',include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

musics/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'music'
urlpatterns = [
    path('',views.index.as_view(),name='index'),
    path('music/<slug:pk>/',views.detail.as_view(),name='detail'),
    path('add/',views.add.as_view(),name='add'),
    path('update/',views.update.as_view(),name='update'),
    path('/<slug:pk>/delete',views.delete,name='delete'),
    path('register',views.register.as_view(),name='register'),
    path('/<slug:pk>/addsong',views.addsong,name='addsong'),
    path('music/<slug:pk>/delete',views.detail.as_view(),name='detail'),
    path('<slug:id>/<slug:name>/songdelete',views.songdelete,name='songdelete'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'acc'

urlpatterns = [
    path('singup/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout_view,name='logout')
]

musics/models.py
from django.db import models
from django.db import models
from django.db.models.fields import FloatField, IntegerField
from django.db.models.fields.related import ForeignKey
from django.urls import reverse
from .templates import *

# Create your models here.
class Albums(models.Model):
    title = models.CharField(max_length=50)
    artist = models.CharField(max_length=50)
    logo = models.CharField(max_length=99999)
    logo_file = models.FileField()

    def get_absolute_url(self):
        return reverse("music:detail", kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.title + ' - ' + self.artist

class song(models.Model):
    album = ForeignKey(Albums, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    length = models.FloatField(null=True)
    is_favorite = models.BooleanField(default=False)
    path = models.FileField(upload_to='media/%y')
    duration = models.FloatField()

    def __str__(self):
        return self.name + ' - ' + str(self.is_favorite)
    

user/models.py
from django.contrib import admin
from django.db import models
from django.contrib.admin import ModelAdmin
# Create your models here.

class LocalUsers(models.Model):
    UserName = models.SlugField()
    Password = models.SlugField()
    FirstName = models.CharField(max_length=50)
    LastName = models.CharField(max_length=50)
    Email = models.SlugField()
    last_login = ''

    class View(admin.ModelAdmin):
        list_display = ['UserName','Email']

    def __str__(self):
        return self.UserName
    

musics/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from django.forms.widgets import PasswordInput

class userform(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput)
    class Meta:
        model = User
        fields = ['username','password','email']

musics/views.py
from django import shortcuts
from musics.models import Albums
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .forms import userform
from django.views.generic import View

# Create your views here.

def delete(request, pk):
    Albums.objects.filter(pk=pk).delete()
    return redirect('/')

class index(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return Albums.objects.all()


class detail(generic.DeleteView):
    template_name = 'detail.html'
    model = Albums.objects.all()
    context_object_name = 'alb'

    def get_queryset(self):
        return Albums.objects.all()
    
class add(CreateView):
    model = Albums
    fields = ['title','artist','logo']
    template_name = 'albums_form.html'
    
class update(UpdateView):
    model = Albums
    fields = ['title','artist','logo']
    template_name = 'albums_form.html'


#class delete(DeleteView):
 #   model = Albums
  #  success_url = reverse_lazy('music:index')
  #  template_name = 'deleted.html'


class register(View):
    form_class = userform
    template_name = 'form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username_r = form.cleaned_data['username']
            password_r = form.cleaned_data['password']
            user.set_password(password_r)
            email = form.cleaned_data['email']
            user.save()

            user = authenticate(username=username_r,password=password_r)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return render('music:index')

        return render(request,self.template_name,{'form':form})

def addsong(request, pk):
    if request.method=='POST':
        SongName = request.POST['songname']
        path = request.POST['file']
        Duration = request.POST['duration']
        album = Albums.objects.get(pk=pk)
        album.song_set.create(name=SongName,path=path,duration=Duration)
        album.save()
        redirect_url = '/music/'+str(pk)
        return redirect(redirect_url)
    else:
        return render(request,'addsong_form.html')

def songdelete(request, id, name):
    album = Albums.objects.get(pk=id)
    album.song_set.get(name=name).delete()
    redirect_url = '/music/'+id
    return redirect(redirect_url)

user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as LoginUser
from django.contrib.auth.models import User
from django.contrib import messages
from .models import LocalUsers
# Create your views here.

from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('/')
    # Redirect to a success page.



def index(request):
    return render(request,'index3.html')

def register(request):
    content = { 'ErrorMessage':None,'UserName':False,'IsBanned':False }
    if request.method=='POST':
        UserName  =  request.POST['UserName']
        Password  =  request.POST['Password']
        FirstName =  request.POST['FirstName']
        LastName  =  request.POST['LastName']
        Email     =  request.POST['Email']

        if User.objects.filter(username=UserName).exists():
            content['ErrorMessage'] = 'This username is already taken'
            return render(request,'forme.html',{'data':content})
        else:
            user = User(username=UserName,first_name=FirstName,last_name=LastName,email=Email)
            user.set_password(Password)
            user.save()
            if user is not None:
              LoginUser(request, user)
              print('loged in')

        return redirect('/')
    else:
        return render(request,'forme.html',{'data':content})


def login(request):
    if request.method=='POST':
        UserName = request.POST['UserName']
        Password = request.POST['Password']
        user = authenticate(username=UserName,password=Password)
        print(user)
        print(UserName)
        print(Password)
        if user is not None:
            LoginUser(request, user)
            return redirect('/')
        else:
            ErrorMessage = 'Username / Password is incorrect'
            return render(request,'logins.html',{'ErrorMessage': ErrorMessage})
    else:
        return render(request,'logins.html')

musics/templates/addsong_form.html
{% extends 'base.html' %}
{% block content %}
<form method='POST' action=''>
{% csrf_token %}
<h3> Register </h3>
{% if data.ErrorMessage %}
<h3> {{ data.ErrorMessage }}
{% endif %}
<div>
Song Name
<input type='text' name='songname'>
</div>
<div>
Path
<input type='file' name='file'>
</div>
<div>
Duration
<input type='text' name='duration'>
</div>
<input type='submit'>
</form>
{% endblock content %}

musics/templates/albums_form.html
{% extends 'base.html' %}
{% block content %}
<form method='post' action='' enctype='multipart/form-data'>
{% csrf_token %}
{{ form }}
<input type='submit'>
</form>
{% endblock content %}

musics/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Hello, world!</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link active" aria-current="page" href="{% url 'acc:logout' %}">logout, {{ user }}</a>
          {% else %}
          <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">login, {{ user }}</a>
          {% endif %}

        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add/">Add Album</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'acc:register' %}">Register</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<section id='cards'>
  {% block content %}
  
  {% endblock content %}
</section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
  </body>
</html>

musics/templates/deleted.html
{% extends 'base.html' %}
{% block content %}
Album is sucsesfully deleted
{% endblock content %}

musics/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<h1> Album : {{ alb.title }} </h1>
{% if error_message %}{{ error_message }}{% endif %}
<form method="post" action="/music/{{ alb.title }}/favorite">
{% csrf_token %}
{% for song in alb.song_set.all %}
<input type="radio" id="song{{ forloop.counter }}"  name="song" value={{ song.id }} />
<label for="song{{ forloop.counter }}">{{ song.name }}</label><br>
{% if song.path %}
<audio controls>
<source src='{{ song.path.url }}'>
</audio>
{% endif %}
{% if song.name %}
<a href=''><i class="fa fa-trash"></a>
{% endif %}
{% endfor %}
<input type='submit'>
</form>
<a href="{% url 'music:addsong' alb.id %}">add new song</a>
{% endblock content %}

musics/templates/form.html
{% extends 'base.html' %}
{% block content %}
<form  method='post' action=''>
{% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">User name</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

musics/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h2> Albums </h2>
<section style='display:flex;flex-wrap:wrap;padding:10px;'>
{% for album in all_album %}
<div class="card" style="width: 18rem;margin:10px;">
  <img src="{{ album.logo }}" class="card-img-top" alt="unable to load">
  <div class="card-body">
    <h5 class="card-title">{{ album.title }}</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="{% url 'music:detail' album.id%}" class="btn btn-primary">Explore</a>
    <a href='{% url 'music:delete' album.id%}'><i class="fa fa-trash"></i></a>
  </div>
</div>
{% endfor %}
</section>
</ul>
{% endblock content %}

user/templates/forme.html
{% extends 'base.html' %}
{% block content %}
<form method='POST' action=''>
{% csrf_token %}
<h3> Register </h3>
{% if data.ErrorMessage %}
<h3> {{ data.ErrorMessage }}
{% endif %}
<div>
UserName :
<input type='text' name='UserName'>
</div>
<div>
Password :
<input type='password' name='Password'>
</div>
<div>
FirstName :
<input type='text' name='FirstName'>
</div>
<div>
LastName :
<input type='text' name='LastName'>
</div>
<div>
Email :
<input type='text' name='Email'>
</div>

<input type='submit'>
</form>
{% endblock content %}

user/templates/index3.html
<h1> Home page </h1>

user/templates/logins.html
{% extends 'base.html' %}
{% block content %}
<form method='POST' action=''>
{% csrf_token %}
<h3> Register </h3>
{% if ErrorMessage %}
<h3> {{ ErrorMessage }}
{% endif %}
<div>
UserName :
<input type='text' name='UserName'>
</div>
<div>
Password :
<input type='text' name='Password'>
</div>
<input type="submit">
</form>
{% endblock content %}